# Generated by Django 6.0.2 on 2026-03-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('SALES', 'Sales'), ('MARKETING', 'Marketing'), ('CUSTOMER_SUPPORT', 'Customer Support')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
