# Generated by Django 6.0.3 on 2026-03-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SALES', 'Sales'), ('MARKETING', 'Marketing'), ('CUSTOMER_SUPPORT', 'Customer Support')], max_length=50),
        ),
    ]
